tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "homeport/tap"
tap "shopify/shopify"
brew "awk"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "d2"
brew "direnv"
brew "fd"
brew "fzf"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "go"
brew "imagemagick"
brew "jq"
brew "lv"
brew "mas"
brew "mise"
brew "mysql"
brew "neovim"
brew "nkf"
brew "tmux"
brew "pdftk-java"
brew "postgresql@17", restart_service: :changed
brew "pwgen"
brew "rename"
brew "ripgrep"
brew "shellcheck"
brew "subversion"
brew "wget"
brew "yq"
brew "z"
brew "zplug"
brew "shopify/shopify/shopify-cli"
brew "shopify/shopify/themekit"
cask "alacritty"
cask "appcleaner"
cask "claude"
cask "cursor"
cask "cyberduck"
cask "deepl"
cask "docker-desktop"
cask "dropbox"
cask "dynalist"
cask "fluid"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-for-powerline-bold"
cask "font-inconsolata-nerd-font"
cask "font-source-sans-pro"
cask "google-chrome"
cask "hammerspoon"
cask "insomnia"
cask "iterm2"
cask "obsidian"
cask "tableplus"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "CotEditor", id: 1024640650
mas "Drafts", id: 1435957248
mas "LINE", id: 539883307
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "MindNode Classic", id: 1289197285
mas "ScreenNote", id: 1258500140
mas "Simplenote", id: 692867256
mas "Slack", id: 803453959
