tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "anyenv"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "direnv"
brew "fd"
brew "fzf"
brew "ghq"
brew "gibo"
brew "python@3.9"
brew "glib"
brew "go"
brew "imagemagick"
brew "jq"
brew "lv"
brew "mas"
brew "mysql", restart_service: true
brew "neovim"
brew "nkf"
brew "postgresql", restart_service: true
brew "ripgrep"
brew "subversion"
brew "tmux"
brew "wget"
brew "yq"
brew "z"
brew "zplug"
cask "appcleaner"
cask "clipy"
cask "cyberduck"
cask "deepl"
cask "docker"
cask "dropbox"
cask "fluid"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-for-powerline-bold"
cask "font-source-sans-pro"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "notion"
cask "obsidian"
cask "tableplus"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "CotEditor", id: 1024640650
mas "LINE", id: 539883307
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "MindNode", id: 1289197285
mas "Slack", id: 803453959
mas "Toggl Track", id: 957734279
mas "Trello", id: 1278508951
